# Generated by Django 4.2.2 on 2024-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_m", models.CharField(blank=True, max_length=30, null=True)),
                ("info_m", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "application_m",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("action_m", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "db_table": "message",
                "managed": False,
            },
        ),
    ]
